#importar la imagen base de python
FROM python:3.12-slim 

#crear en el contenedor la Carpeta de trabajo 
WORKDIR /app

#copiar los requerimientos al contenedor 
#el "." significa copiarlo con el mismo nombre 
COPY requirements.txt . 

#instalamos las dependencias de FASTAPI
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo del servidor
COPY ./app ./app

#exponer el puerto de trabajo 
EXPOSE 5000

#comando que necesita ejecutar para levantar el servidor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

